import json

path = 'modelo-gbm-brasileiro/treino_gbm_brasileiro.ipynb'
with open(path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Localiza a célula pelo ID ou pelo cabeçalho da Etapa 5
target_cell = None
for cell in nb['cells']:
    if cell.get('id') == 'cell-features' or (cell['cell_type'] == 'code' and any('5. Feature Engineering' in line for line in cell['source'])):
        target_cell = cell
        break

if target_cell:
    new_source = [
        "# ============================================================\n",
        "# 5. Feature Engineering (Versão Final Turbo — Brasil)\n",
        "#    - Diferenciação de Keywords (Hostname vs Path)\n",
        "#    - Selos de confiança: .gov.br, .edu.br, .org.br\n",
        "#    - Resolução definitiva de Falsos Positivos\n",
        "# ============================================================\n",
        "\n",
        "def extract_features(url: str) -> dict:\n",
        "    \"\"\"Extrai features otimizadas para marcas brasileiras e instituições.\"\"\"\n",
        "    raw = url\n",
        "    if not url.startswith(('http://', 'https://')):\n",
        "        url = 'http://' + url\n",
        "\n",
        "    try:\n",
        "        parsed = urlparse(url)\n",
        "        ext = tldextract.extract(url)\n",
        "    except Exception:\n",
        "        parsed = urlparse('http://invalid')\n",
        "        ext = tldextract.extract('http://invalid')\n",
        "\n",
        "    # Convertemos para minúsculo para busca de keywords\n",
        "    hostname = (parsed.hostname or '').lower()\n",
        "    path     = (parsed.path or '').lower()\n",
        "    query    = (parsed.query or '').lower()\n",
        "\n",
        "    features = {}\n",
        "\n",
        "    # --- ESTRUTURA BÁSICA ---\n",
        "    features['url_length']      = len(raw)\n",
        "    features['hostname_length'] = len(hostname)\n",
        "    features['path_length']     = len(path)\n",
        "    features['query_length']    = len(query)\n",
        "    features['path_depth']      = path.count('/') - 1 if path else 0\n",
        "    features['num_params']      = query.count('=') if query else 0\n",
        "\n",
        "    # --- CARACTERES ---\n",
        "    features['num_dots']        = raw.count('.')\n",
        "    features['num_hyphens']     = raw.count('-')\n",
        "    features['num_underscores'] = raw.count('_')\n",
        "    features['num_slashes']     = raw.count('/')\n",
        "    features['num_ats']         = raw.count(' @')\n",
        "    features['num_equals']      = raw.count('=')\n",
        "    features['num_digits']      = sum(c.isdigit() for c in raw)\n",
        "    features['num_special']     = sum(not c.isalnum() and c not in './-_' for c in raw)\n",
        "\n",
        "    # --- DIFERENCIAÇÃO LOCAL (Resolve League of Legends e Bancos) ---\n",
        "    features['num_hyphens_domain'] = hostname.count('-')\n",
        "    features['num_hyphens_path']   = path.count('-')\n",
        "    features['num_dots_hostname']  = hostname.count('.')\n",
        "\n",
        "    # --- SELOS DE CONFIANÇA (Resolve Planalto, Receita e UFPR) ---\n",
        "    features['is_gov_br']        = int(ext.suffix == 'gov.br')\n",
        "    features['is_com_br']        = int(ext.suffix == 'com.br')\n",
        "    features['is_edu_br']        = int(ext.suffix == 'edu.br')\n",
        "    features['is_org_br']        = int(ext.suffix == 'org.br')\n",
        "\n",
        "    features['subdomain_length'] = len(ext.subdomain)\n",
        "    features['domain_length']    = len(ext.domain)\n",
        "    features['tld_length']       = len(ext.suffix)\n",
        "    features['num_subdomains']   = ext.subdomain.count('.') + 1 if ext.subdomain else 0\n",
        "\n",
        "    # --- PROPORÇÕES E ENTROPIA ---\n",
        "    features['digit_ratio']   = features['num_digits']  / max(len(raw), 1)\n",
        "    features['special_ratio'] = features['num_special'] / max(len(raw), 1)\n",
        "    if len(raw) > 0:\n",
        "        prob = [raw.count(c) / len(raw) for c in set(raw)]\n",
        "        features['entropy'] = -sum(p * np.log2(p) for p in prob if p > 0)\n",
        "    else:\n",
        "        features['entropy'] = 0\n",
        "\n",
        "    # --- PADRÕES SUSPEITOS (Da sua lista UCI) ---\n",
        "    features['has_ip'] = int(bool(re.match(r'^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$', hostname)))\n",
        "    features['has_at_sign']               = int(' @' in raw)\n",
        "    features['has_double_slash_redirect'] = int('//' in raw[8:])\n",
        "    features['has_hex_encoding']          = int('%' in raw)\n",
        "    features['has_https']                 = int(raw.startswith('https'))\n",
        "    features['has_www']                   = int('www.' in hostname)\n",
        "    features['has_prefix_suffix']         = int('-' in hostname)\n",
        "\n",
        "    shorteners = ['bit.ly', 'goo.gl', 'shorte.st', 'go2l.ink', 'x.co', 'ow.ly', 't.co', 'tinyurl.com', 'tr.im', 'is.gd', 'cli.re']\n",
        "    features['has_shortener'] = int(any(s in hostname for s in shorteners))\n",
        "\n",
        "    try:\n",
        "        port = parsed.port\n",
        "    except ValueError:\n",
        "        port = None\n",
        "    features['has_port'] = int(port is not None and port not in [80, 443])\n",
        "\n",
        "    # Extensão suspeita\n",
        "    suspicious_ext = ['.exe', '.zip', '.rar', '.js', '.php', '.cgi', '.asp', '.aspx', '.scr', '.bat', '.cmd']\n",
        "    features['has_suspicious_ext'] = int(any(path.endswith(e) for e in suspicious_ext))\n",
        "\n",
        "    # --- PALAVRAS-CHAVE (Turbo: Localização da Marca vs Golpe) ---\n",
        "    phishing_keywords = [\n",
        "        'login', 'signin', 'verify', 'account', 'update', 'secure', 'confirm', 'password', 'suspend',\n",
        "        'conta', 'acesso', 'seguro', 'atualizar', 'liberar', 'bloqueio', 'recadastro', 'atencao',\n",
        "        'beneficio', 'auxilio', 'urgente', 'caixa', 'bradesco', 'itau', 'nubank', 'santander'\n",
        "    ]\n",
        "\n",
        "    # ESSENCIAL: Se 'itau' está no hostname, é marca. Se está no path, é golpe.\n",
        "    features['keywords_hostname'] = sum(kw in hostname for kw in phishing_keywords)\n",
        "    features['keywords_path']     = sum(kw in path for kw in phishing_keywords)\n",
        "    features['keywords_query']    = sum(kw in query for kw in phishing_keywords)\n",
        "\n",
        "    # --- ANÁLISE DE TOKENS ---\n",
        "    tokens = re.split(r'[.\\-_/=?&]', raw)\n",
        "    features['num_tokens']       = len(tokens)\n",
        "    features['avg_token_length'] = np.mean([len(t) for t in tokens if t]) if tokens else 0\n",
        "    features['max_token_length'] = max((len(t) for t in tokens if t), default=0)\n",
        "\n",
        "    return features\n",
        "\n",
        "print('Extraindo features das URLs...')\n",
        "t0 = time.time()\n",
        "\n",
        "url_col = 'url' if 'url' in df.columns else 'text'\n",
        "feature_rows = df[url_col].apply(extract_features)\n",
        "df_features  = pd.DataFrame(feature_rows.tolist())\n",
        "\n",
        "print(f'Features extraídas em {time.time() - t0:.1f}s')\n",
        "print(f'Shape: {df_features.shape} — {df_features.shape[1]} features')\n",
        "df_features.head()"
    ]
    target_cell['source'] = new_source
    print("Célula atualizada com sucesso.")

with open(path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
